import math
from typing import Tuple, List, Dict, Sequence

Coordinate = Tuple[float, float]


#------------------------------------
# Constants for LCOE calculation
# ------------------------------------

plant_capacity = 50_000 # rated power of one Vestas V110-2.0 MW turbine

CAPEX_TOTAL_PER_KW = 1968
BASE_CAPEX_USD = 98_400_000 #1968 x 50,000 kW



OPEX_PER_KW_YEAR = 43
ANNUAL_OPEX_USD = 2_150_000 #43 x 50k

PROJECT_LIFE_YEARS = 25
REAL_WACC = 0.0366
REAL_FCR = 0.065 # using this instead of WACC 
# all above are based on the NREL 2024 cost of wind energy report

CABLE_COST_PER_M = 324.68 #https://www.wireandcableyourway.com/1-0-mv-105-25kv-35kv-epr-pvc-power-cable-w-copper-tape-shield-133-100-insulation
# for 3 conductors, 3 x 20.22 x 3.28 = 199 and then add 20% for insulation and shielding = 239. Add 35% for installation = 324.68


ROAD_COST_PER_M = 88 # https://www.dot.state.tx.us/insdtdot/geodist/ama/cserve/bidprice/s_0201.htm? 

SUBSTATION = (0.0, 1237.5) #hypothetical coordinates for substation location
ROAD_ENTRY = (0.0, 1237.5) #hypothetical coordinates for road entry point


def distance(point_1, point_2):
    """Calculate the straight-line distance between two coordinates."""
    return math.hypot(
        point_2[0] - point_1[0],
        point_2[1] - point_1[1],
    )


def minimum_spanning_tree_length(points):
    """
    Estimate the shortest shared network connecting all supplied points.

    Layout coordinates must be in metres.
    """

    points = [tuple(map(float, point)) for point in points]

    if len(points) <= 1:
        return 0.0

    connected = [False] * len(points)
    shortest_connection = [math.inf] * len(points)

    shortest_connection[0] = 0.0
    total_length = 0.0

    for _ in range(len(points)):
        next_point = -1
        shortest_edge = math.inf

        for index in range(len(points)):
            if (
                not connected[index]
                and shortest_connection[index] < shortest_edge
            ):
                shortest_edge = shortest_connection[index]
                next_point = index

        if next_point == -1:
            raise RuntimeError("Could not construct the network.")

        connected[next_point] = True
        total_length += shortest_edge

        for other_point in range(len(points)):
            if not connected[other_point]:
                edge_length = distance(
                    points[next_point],
                    points[other_point],
                )

                if edge_length < shortest_connection[other_point]:
                    shortest_connection[other_point] = edge_length

    return total_length


def calculate_lcoe(layout, annual_aep_mwh):
    """
    Calculate the LCOE of one supplied turbine layout.

    Parameters
    ----------
    layout:
        Turbine coordinates generated by the GA or layouts.py.

    annual_aep_mwh:
        AEP of the same layout in MWh/year.

    Returns
    -------
    LCOE in USD/MWh.
    """

    if layout is None or len(layout) == 0:
        raise ValueError("The layout cannot be empty.")

    if annual_aep_mwh <= 0:
        raise ValueError("Annual AEP must be greater than zero.")

    turbine_coordinates = [
        tuple(map(float, position))
        for position in layout
    ]

    cable_length_m = minimum_spanning_tree_length(
        [SUBSTATION, *turbine_coordinates]
    )

    road_length_m = minimum_spanning_tree_length(
        [ROAD_ENTRY, *turbine_coordinates]
    )

    cable_cost = cable_length_m * CABLE_COST_PER_M
    road_cost = road_length_m * ROAD_COST_PER_M

    total_capex = BASE_CAPEX_USD + cable_cost + road_cost

    annual_project_cost = (
        REAL_FCR * total_capex
        + ANNUAL_OPEX_USD
    )

    lcoe_usd_per_mwh = annual_project_cost / annual_aep_mwh

    return lcoe_usd_per_mwh


def calculate_staggered_lcoe():
    """
    Calculate the staggered-layout LCOE when this file is run directly.
    """

    # Imported here to avoid unnecessary imports when the GA only calls
    # calculate_lcoe().
    from layouts import staggered_layout
    from main import calculate_aep, load_real_wind_data

    print("Loading wind data...")

    speeds, directions, samples = load_real_wind_data()
    layout = staggered_layout()

    print(f"Loaded {samples} wind samples.")
    print("Calculating staggered-layout AEP...")

    staggered_aep, _ = calculate_aep(
        layout,
        speeds,
        directions,
    )

    staggered_lcoe = calculate_lcoe(
        layout=layout,
        annual_aep_mwh=staggered_aep,
    )

    print("\n===== STAGGERED LAYOUT LCOE =====")
    print(f"LCOE: ${staggered_lcoe:,.2f}/MWh")

    return staggered_lcoe


if __name__ == "__main__":
    calculate_staggered_lcoe()